"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var numberSet = '0123456789';
exports.numberSet = numberSet;
var lowercaseCharactorSet = 'abcdefghijklmnopqrstuvwxyz';
exports.lowercaseCharactorSet = lowercaseCharactorSet;
var uppercaseCharactorset = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
exports.uppercaseCharactorset = uppercaseCharactorset;
var alphanumericSet = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
exports.alphanumericSet = alphanumericSet;
var hexSet = '0123456789abcdef';
exports.hexSet = hexSet;
var base64Set = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/=';
exports.base64Set = base64Set;
var specialCharactorSet = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~';
exports.specialCharactorSet = specialCharactorSet;
